# Generated by Django 5.1 on 2026-06-02 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("oil_change", "Oil Change"),
                            ("tire_change", "Tire Change"),
                            ("brake_service", "Brake Service"),
                            ("diagnostic", "Diagnostic"),
                            ("repair", "Repair"),
                            ("technical_inspection", "Technical Inspection"),
                            ("body_work", "Body Work"),
                            ("electrical", "Electrical"),
                            ("transmission", "Transmission"),
                            ("engine", "Engine Work"),
                            ("cooling", "Cooling System"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        help_text="Mileage at time of service (km)"
                    ),
                ),
                ("service_date", models.DateField(db_index=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("service_center_name", models.CharField(blank=True, max_length=200)),
                ("technician_name", models.CharField(blank=True, max_length=200)),
                ("parts_replaced", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "service_records",
                "ordering": ["-service_date"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-service_date"],
                        name="service_rec_vehicle_b9cd76_idx",
                    ),
                    models.Index(
                        fields=["service_type"], name="service_rec_service_d7a11d_idx"
                    ),
                ],
            },
        ),
    ]
