# Generated by Django 5.1 on 2026-06-02 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("damage_parts", models.JSONField(default=list)),
                ("accident_date", models.DateField(db_index=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                (
                    "mileage_at_accident",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("report_number", models.CharField(blank=True, max_length=100)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accidents",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_accidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accident_date"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-accident_date"],
                        name="accidents_a_vehicle_b8a4e4_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="accidents_a_severit_9d8b81_idx"
                    ),
                    models.Index(
                        fields=["verified"], name="accidents_a_verifie_90225e_idx"
                    ),
                ],
            },
        ),
    ]
