# Generated by Django 5.0.1 on 2026-06-02 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vin_code",
                    models.CharField(
                        db_index=True,
                        help_text="17-character Vehicle Identification Number",
                        max_length=17,
                        unique=True,
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("brand", models.CharField(db_index=True, max_length=100)),
                ("model", models.CharField(db_index=True, max_length=100)),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                ("color", models.CharField(max_length=50)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("lpg", "LPG"),
                            ("cng", "CNG"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                            ("semi_auto", "Semi-Automatic"),
                            ("cvt", "CVT"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "engine_volume",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        default=0, help_text="Current mileage in km"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stolen", "Stolen"),
                            ("written_off", "Written Off"),
                            ("scrapped", "Scrapped"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("ownership_count", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleOwnershipHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_name", models.CharField(max_length=200)),
                ("acquired_at", models.DateField()),
                ("released_at", models.DateField(blank=True, null=True)),
                (
                    "transfer_mileage",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_history",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_ownership_history",
                "ordering": ["-acquired_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["brand", "model"], name="vehicles_brand_eef742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["year"], name="vehicles_year_fa878c_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["status"], name="vehicles_status_e44f2b_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["brand", "model", "year"], name="vehicles_brand_3ad90e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleownershiphistory",
            index=models.Index(
                fields=["vehicle", "-acquired_at"],
                name="vehicle_own_vehicle_e9548a_idx",
            ),
        ),
    ]
