# Generated by Django 6.0.5 on 2026-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Is this vehicle record verified by staff?"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Suggested price or valuation",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="workshop_visits",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Manual count of workshop visits"
            ),
        ),
    ]
