# Generated by Django 6.0.5 on 2026-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_vehicle_is_verified_vehicle_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="Currency code for the price (e.g. USD, EUR)",
                max_length=3,
            ),
        ),
    ]
