# Generated by Django 6.0.5 on 2026-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_vehicle_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("TRY", "TRY"),
                    ("CHF", "CHF"),
                ],
                default="USD",
                help_text="Currency code for the price (e.g. USD, EUR)",
                max_length=3,
            ),
        ),
    ]
