# Generated by Django 5.1 on 2026-06-02 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inspector_name", models.CharField(max_length=128)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("conditional", "Conditional Pass"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(help_text="Rating out of 10"),
                ),
                ("inspection_date", models.DateField(db_index=True)),
                ("next_inspection_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "inspections",
                "ordering": ["-inspection_date"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-inspection_date"],
                        name="inspections_vehicle_87b3ea_idx",
                    ),
                    models.Index(
                        fields=["result"], name="inspections_result_438650_idx"
                    ),
                ],
            },
        ),
    ]
